language: php

php:
 - 5.4
 - 5.5
 - 5.6
 - hhvm
 - nightly

before_script:
 - echo 'date.timezone = "UTC"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
 - composer install

script:
 - vendor/bin/phpspec run
