language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

before_script:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then printf "\n" | pecl install imagick; fi'
  - composer install

script:
  - vendor/bin/phpspec run
